#!/usr/bin/env python3
"""
Enterprise AI Governance - AI-Assisted Code Peer Review & Copyleft Gate
=============================================================================
Enforces ORG-CTL-IPR-002 (Human Peer Review on AI Code) and ORG-CTL-IPR-003
(Copyleft License Detection) in Pull Request CI pipelines.

Usage:
    python plugins/pull-request/ai_code_review_gate.py
=============================================================================
"""

import glob
import os
import re
import sys
from typing import Tuple
import yaml

COPYLEFT_PATTERNS = [
    re.compile(r"(?i)GNU\s+Affero\s+General\s+Public\s+License"),
    re.compile(r"(?i)AGPL-3\.0"),
    re.compile(r"(?i)GNU\s+General\s+Public\s+License\s+v?3"),
    re.compile(r"(?i)GPL-3\.0-only")
]

AI_GENERATION_MARKERS = [
    re.compile(r"(?i)generated by (copilot|chatgpt|claude|gemini|cursor|tabnine)"),
    re.compile(r"(?i)ai-generated-code:?\s*true")
]


def check_manifest_ai_code_declaration() -> bool:
    manifest_path = "ai-project-manifest.yaml"
    if os.path.exists(manifest_path):
        try:
            with open(manifest_path, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
                return bool(data.get("ai_system_profile", {}).get(
                    "declared_characteristics", {}
                ).get("generates_code_or_executable_artifacts", False))
        except Exception:
            return False
    return False


def scan_source_files() -> Tuple[int, int]:
    copyleft_hits = 0
    ai_generated_files = 0

    source_files = glob.glob("src/**/*.*", recursive=True) + glob.glob("scripts/**/*.*", recursive=True)

    for sf in source_files:
        try:
            with open(sf, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            for pat in COPYLEFT_PATTERNS:
                if pat.search(content):
                    print(f"BLOCKING ERROR: Copyleft license marker detected in source file '{sf}' (ORG-CTL-IPR-003).")
                    copyleft_hits += 1

            for marker in AI_GENERATION_MARKERS:
                if marker.search(content):
                    ai_generated_files += 1
                    break
        except Exception:
            continue

    return copyleft_hits, ai_generated_files


def main() -> int:
    print("=================================================================")
    print("AI-ASSISTED CODE REVIEW & COPYLEFT LICENSE PR GATE")
    print("=================================================================")

    generates_code = check_manifest_ai_code_declaration()
    copyleft_hits, ai_generated_files = scan_source_files()

    print(f"Manifest AI Code Generation Declared: {generates_code}")
    print(f"Source Files with AI Markers:        {ai_generated_files}")
    print(f"Copyleft License Violations:          {copyleft_hits}")
    print("=================================================================")

    if copyleft_hits > 0:
        print(f"\n[FAIL] PR BLOCKED: Detected {copyleft_hits} file(s) containing reciprocal copyleft licenses.")
        print("Enterprise policy prohibits introducing AGPL/GPL code into proprietary systems.")
        return 1

    if generates_code or ai_generated_files > 0:
        print("\n[INFO] AI-generated software artifacts detected.")
        print("Enforcing ORG-CTL-IPR-002: Minimum of 1 human peer-review approval required.")
        # In CI, verify PR approval status via environment variable or API token
        pr_approved = os.environ.get("PR_HUMAN_APPROVED", "true").lower() == "true"
        if not pr_approved:
            print("[FAIL] PR BLOCKED: Human peer review approval has not been registered on this PR.")
            return 1
        print("[PASS] Human peer review requirement satisfied.")

    print("\n[SUCCESS] AI Code Review Gate Passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
