#!/usr/bin/env python3
"""
Enterprise AI Governance - Interactive Project Initialization Wizard
=============================================================================
Provides a dead-simple, 1-minute 'npm init' style CLI experience for
development teams adopting enterprise AI governance.

Usage:
    python project-kit/init.py
    python project-kit/init.py --quick   (Uses sensible defaults non-interactively)
=============================================================================
"""

import os
import sys
import json
import subprocess
from pathlib import Path


def prompt_text(question: str, default: str) -> str:
    val = input(f"{question} [{default}]: ").strip()
    return val if val else default


def prompt_bool(question: str, default: bool = False) -> bool:
    default_str = "Y/n" if default else "y/N"
    val = input(f"{question} [{default_str}]: ").strip().lower()
    if not val:
        return default
    return val in ["y", "yes", "true", "1"]


def main():
    print("\n" + "=" * 65)
    print("  Enterprise AI Governance - 1-Minute Project Setup Wizard")
    print("=" * 65)
    print("Answer 5 quick questions to configure governance for your AI project.\n")

    quick_mode = "--quick" in sys.argv

    if quick_mode:
        project_name = "My AI Project"
        project_id = "SYS-APP-MY-AI-01"
        owner_name = "AI Engineering Team"
        owner_email = "ai-team@enterprise.com"
        archetype_choice = "1"
        has_pii = False
        in_eu = False
        has_tools = False
    else:
        project_name = prompt_text("1. What is the name of your AI application?", "Customer Support AI")
        slug = "".join(c if c.isalnum() else "-" for c in project_name.lower()).strip("-")
        project_id = prompt_text("2. What is your System Inventory ID?", f"SYS-APP-{slug.upper()}-01")
        owner_name = prompt_text("3. Lead Developer / Owner Name", "Lead Engineer")
        owner_email = prompt_text("4. Owner Corporate Email", "engineer@enterprise.com")
        
        print("\n5. What kind of AI architecture are you building?")
        print("   [1] Generative LLM (Chatbot, Text Generation, Summarization)")
        print("   [2] RAG (Knowledge base with embeddings and vector database)")
        print("   [3] Predictive ML (Tabular classification, regression, scoring)")
        print("   [4] Autonomous Agent (LLM invoking external tools, APIs, SQL)")
        archetype_choice = prompt_text("   Select architecture", "1")

        has_pii = prompt_bool("\n6. Will this system process customer personal data (PII)?", False)
        in_eu = prompt_bool("7. Will this system be used by or affect people in the European Union?", False)
        has_tools = archetype_choice == "4" or prompt_bool("8. Does this system execute external tools, APIs, or database writes?", False)

    archetype_map = {
        "1": ("generative_llm", "tier_2_moderate"),
        "2": ("rag_knowledge", "tier_2_moderate"),
        "3": ("predictive_tabular", "tier_2_moderate"),
        "4": ("autonomous_agent", "tier_3_high"),
    }
    archetype, risk_tier = archetype_map.get(archetype_choice, ("generative_llm", "tier_2_moderate"))

    # Construct clean, minimal manifest
    manifest_yaml = f"""# Enterprise AI Governance Project Manifest
# Generated by project-kit/init.py
schema_version: "2020-12"
project_id: "{project_id}"
project_name: "{project_name}"
baseline_version: "v0.1.0-draft"

owners:
  business_owner:
    name: "{owner_name}"
    email: "{owner_email}"
    role_placeholder: "[ROLE: Business Owner]"
  technical_lead:
    name: "{owner_name}"
    email: "{owner_email}"
    role_placeholder: "[ROLE: Technical Lead]"

ai_system_profile:
  lifecycle_status: "development"
  risk_tier: "{risk_tier}"
  archetype: "{archetype}"
  
  declared_characteristics:
    processes_personal_data: {str(has_pii).lower()}
    executes_tools_or_agents: {str(has_tools).lower()}
    generates_user_facing_content: {str(archetype in ['generative_llm', 'rag_knowledge', 'autonomous_agent']).lower()}
    makes_automated_decisions: false
    generates_code_or_executable_artifacts: false

governance_bindings:
  overlays:
    geography:"""
    
    if in_eu:
        manifest_yaml += """
      - overlay_id: "ORG-OVL-GEO-EU-001"
        version: "v0.1.0-draft"
"""
    else:
        manifest_yaml += " []\n"

    manifest_yaml += """    sector: []
    risk_tier:"""

    if risk_tier == "tier_3_high":
        manifest_yaml += """
      - overlay_id: "ORG-OVL-RSK-TIER3-001"
        version: "v0.1.0-draft"
"""
    else:
        manifest_yaml += " []\n"

    manifest_yaml += """  exceptions: []
"""

    manifest_path = Path("ai-project-manifest.yaml")
    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(manifest_yaml)

    print(f"\n[OK] Created clean manifest: {manifest_path.resolve()}")

    # Determine paths for resolver
    repo_root = Path(__file__).resolve().parent.parent
    resolver_script = repo_root / "project-kit" / "resolver" / "resolve.py"
    baseline_dir = repo_root / "baseline" / "controls"
    overlays_dir = repo_root / "overlays"

    print("\n[..] Running automated resolver to calculate your project's policy snapshot...")
    cmd = [
        sys.executable,
        str(resolver_script),
        "--manifest", str(manifest_path),
        "--baseline-dir", str(baseline_dir),
        "--overlays-dir", str(overlays_dir),
        "--output", "effective-policy-snapshot.json"
    ]

    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode == 0:
        print("[OK] Computed: effective-policy-snapshot.json")
        try:
            with open("effective-policy-snapshot.json", "r", encoding="utf-8") as sf:
                sdata = json.load(sf)
            active_count = sdata.get("total_active_controls", 0)
            snapshot_hash = sdata.get("snapshot_integrity_hash", "")[:12]
        except Exception:
            active_count = "N/A"
            snapshot_hash = "N/A"

        print("\n" + "=" * 65)
        print("  SETUP COMPLETE! YOUR AI PROJECT IS NOW GOVERNED")
        print("=" * 65)
        print(f"  * Project ID:             {project_id}")
        print(f"  * Architecture:           {archetype} ({risk_tier})")
        print(f"  * Active Controls:        {active_count} controls calculated automatically")
        print(f"  * Snapshot Hash:          {snapshot_hash}...")
        print("=" * 65)
        print("\nWHAT TO DO NEXT (Just 2 Steps!):")
        print("  1. git add ai-project-manifest.yaml effective-policy-snapshot.json")
        print("  2. git commit -m 'feat: add enterprise AI governance baseline'")
        print("\nThat's it! Your project is now registered and compliant.\n")
    else:
        print(f"[ERROR] Resolver failed: {res.stderr}")
        sys.exit(1)


if __name__ == "__main__":
    main()
